# Generated by Django 5.2.6 on 2025-11-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customusermodel",
            name="first_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="customusermodel",
            name="last_name",
            field=models.CharField(max_length=150),
        ),
    ]
